In [4]:
#importing important libraries
import numpy as np
import matplotlib as mp
from PIL import Image


# Step 1: Improting Image

In [6]:
#getting file path
path = input("please enter the file path of the image or n if image is in current directory with name 'image.png'")

#opening image
if path == "n":
    #opening image
    img = Image.open('image.png').convert('L')
    #saving for future reference as needed
    img.save('greyscale.png')
else:
    #opening image
    img = Image.open(path).convert('L')
    #saving for future reference as needed
    img.save('greyscale.png')



# Step 2: Creating data array

In [8]:
#using numpy to make 2D array of all pixel values
imgArray = np.asarray(img)

#printing for confirmation of proper form
print(imgArray)

[[ 71  71  71 ...  65  62 104]
 [ 37  37  37 ...  31  28  70]
 [ 45  45  45 ...  39  36  78]
 ...
 [ 51  51  51 ...  41  36  77]
 [ 38  38  37 ...  29  24  65]
 [ 99  99  98 ...  91  86 127]]


# Step 3: Defining Scale

# Step 4: Creating STL and visualizing output